# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3516af88212574093831e79752d17b81a1562f1ab105d661c726210e54307c7af9a12446321fcc46a4a3a221f60c5f68194dc37a01c8029f4aa9ac43177184a

test:
  secret_key_base: bdd23a5533a7f44ccb5b921d2882c411b7537e7e477113d7128fdc217a80d998568ad80d4af4a53e1ff4ed555133af4aa2e64b1f7de53c042f77e4caa681b6cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
