require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe HistoricalDataController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # HistoricalDatum. As you add validations to HistoricalDatum, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # HistoricalDataController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all historical_data as @historical_data" do
      historical_datum = HistoricalDatum.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:historical_data)).to eq([historical_datum])
    end
  end

  describe "GET #show" do
    it "assigns the requested historical_datum as @historical_datum" do
      historical_datum = HistoricalDatum.create! valid_attributes
      get :show, {:id => historical_datum.to_param}, valid_session
      expect(assigns(:historical_datum)).to eq(historical_datum)
    end
  end

  describe "GET #new" do
    it "assigns a new historical_datum as @historical_datum" do
      get :new, {}, valid_session
      expect(assigns(:historical_datum)).to be_a_new(HistoricalDatum)
    end
  end

  describe "GET #edit" do
    it "assigns the requested historical_datum as @historical_datum" do
      historical_datum = HistoricalDatum.create! valid_attributes
      get :edit, {:id => historical_datum.to_param}, valid_session
      expect(assigns(:historical_datum)).to eq(historical_datum)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new HistoricalDatum" do
        expect {
          post :create, {:historical_datum => valid_attributes}, valid_session
        }.to change(HistoricalDatum, :count).by(1)
      end

      it "assigns a newly created historical_datum as @historical_datum" do
        post :create, {:historical_datum => valid_attributes}, valid_session
        expect(assigns(:historical_datum)).to be_a(HistoricalDatum)
        expect(assigns(:historical_datum)).to be_persisted
      end

      it "redirects to the created historical_datum" do
        post :create, {:historical_datum => valid_attributes}, valid_session
        expect(response).to redirect_to(HistoricalDatum.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved historical_datum as @historical_datum" do
        post :create, {:historical_datum => invalid_attributes}, valid_session
        expect(assigns(:historical_datum)).to be_a_new(HistoricalDatum)
      end

      it "re-renders the 'new' template" do
        post :create, {:historical_datum => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested historical_datum" do
        historical_datum = HistoricalDatum.create! valid_attributes
        put :update, {:id => historical_datum.to_param, :historical_datum => new_attributes}, valid_session
        historical_datum.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested historical_datum as @historical_datum" do
        historical_datum = HistoricalDatum.create! valid_attributes
        put :update, {:id => historical_datum.to_param, :historical_datum => valid_attributes}, valid_session
        expect(assigns(:historical_datum)).to eq(historical_datum)
      end

      it "redirects to the historical_datum" do
        historical_datum = HistoricalDatum.create! valid_attributes
        put :update, {:id => historical_datum.to_param, :historical_datum => valid_attributes}, valid_session
        expect(response).to redirect_to(historical_datum)
      end
    end

    context "with invalid params" do
      it "assigns the historical_datum as @historical_datum" do
        historical_datum = HistoricalDatum.create! valid_attributes
        put :update, {:id => historical_datum.to_param, :historical_datum => invalid_attributes}, valid_session
        expect(assigns(:historical_datum)).to eq(historical_datum)
      end

      it "re-renders the 'edit' template" do
        historical_datum = HistoricalDatum.create! valid_attributes
        put :update, {:id => historical_datum.to_param, :historical_datum => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested historical_datum" do
      historical_datum = HistoricalDatum.create! valid_attributes
      expect {
        delete :destroy, {:id => historical_datum.to_param}, valid_session
      }.to change(HistoricalDatum, :count).by(-1)
    end

    it "redirects to the historical_data list" do
      historical_datum = HistoricalDatum.create! valid_attributes
      delete :destroy, {:id => historical_datum.to_param}, valid_session
      expect(response).to redirect_to(historical_data_url)
    end
  end

end
